/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTip: typeof import('element-plus/es')['ElTip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileSelector: typeof import('./src/components/FileSelector.vue')['default']
    FileSelects: typeof import('./src/components/FileSelects.vue')['default']
  }
}
